=== antonioalfonsogr/lenguaje_marcas_20_21/U1/U1_T3_VALIDATING_XML_FILES_WITH_XML_Schema/Exercise_2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Author" type="xs:string" maxOccurs="unbounded" />
                            <xs:element name="Year" type="xs:integer" />
                            <xs:element name="Title" type="xs:string" />
                            <xs:element name="Place_of_Publication" type="xs:string" />
                            <xs:element name="Publisher" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            </xs:complexType>
    </xs:element>
</xs:schema>

=== antonioalfonsogr/lenguaje_marcas_20_21/U1/U1_T3_VALIDATING_XML_FILES_WITH_XML_Schema/Exercise_2.xml
<?xml version="1.0" encoding="utf-8"?>

<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Exercise_2.xsd">

    <Book>
        <Author>Antoniou, G.</Author>
        <Author>F. van Harmelen</Author>
        <Year>2004</Year>
        <Title>A Semantic Web Primer</Title>
        <Place_of_Publication>Cambridge, MA</Place_of_Publication>
        <Publisher>MIT Press</Publisher>
    </Book>

    <Book>
        <Author>Daconts, M.C.</Author>
        <Author>L.J. Orbst</Author>
        <Author>K.T. Smith</Author>
        <Year>2003</Year>
        <Title>The Semantic Web: A Guide to the Future of XML, Web Services, and Knowledge Management</Title>
        <Place_of_Publication>New York</Place_of_Publication>
        <Publisher>Wiley</Publisher>
    </Book>

</Books>
