=== antonioalfonsogr/lenguaje_marcas_20_21/U1/U1_T3_VALIDATING_XML_FILES_WITH_XML_Schema/Exercise_1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Members">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Member" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Name" type="xs:string" />
                            <xs:element name="Years_of_Membership" type="xs:integer" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            </xs:complexType>
    </xs:element>
</xs:schema>

=== antonioalfonsogr/lenguaje_marcas_20_21/U1/U1_T3_VALIDATING_XML_FILES_WITH_XML_Schema/Exercise_1.xml
<?xml version="1.0" encoding="utf-8"?>

<Members xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Exercise_1.xsd">

    <Member>
        <Name>Chris Smith</Name>
        <Years_of_Membership>4</Years_of_Membership>
    </Member>

    <Member>
        <Name>Judi Zimmerman</Name>
        <Years_of_Membership>5</Years_of_Membership>
    </Member>

    <Member>
        <Name>Michael Calder</Name>
        <Years_of_Membership>3</Years_of_Membership>
    </Member>

</Members>
